cmake_minimum_required(VERSION 3.24)
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef fixture_id)
set(fixture "${CMAKE_CURRENT_BINARY_DIR}/spaceledger-cli-${fixture_id}")
file(MAKE_DIRECTORY "${fixture}/data" "${fixture}/other")
file(WRITE "${fixture}/data/example.txt" "first version")
set(database "${fixture}/history.db")

function(run expected)
  execute_process(COMMAND "${SPACELEDGER_EXE}" ${ARGN}
    RESULT_VARIABLE status OUTPUT_VARIABLE output ERROR_VARIABLE errors ENCODING UTF-8)
  if(NOT "${status}" STREQUAL "${expected}")
    message(FATAL_ERROR "CLI returned ${status}, expected ${expected}: ${ARGN}\n${output}\n${errors}")
  endif()
  set(last_output "${output}" PARENT_SCOPE)
endfunction()

run(0 scan "${fixture}/data" --database "${database}")
if(NOT last_output MATCHES "Saved snapshot 1")
  message(FATAL_ERROR "First scan ID missing: ${last_output}")
endif()
file(APPEND "${fixture}/data/example.txt" " +seven")
run(0 scan "${fixture}/data" --database "${database}")
run(0 scans --database "${database}")
if(NOT last_output MATCHES "1  " OR NOT last_output MATCHES "2  ")
  message(FATAL_ERROR "Scan listing missing IDs: ${last_output}")
endif()
run(0 scans --json --database "${database}")
string(JSON json_count LENGTH "${last_output}" snapshots)
string(JSON first_id GET "${last_output}" snapshots 0 id)
if(NOT json_count EQUAL 2 OR NOT first_id EQUAL 1)
  message(FATAL_ERROR "Invalid scan JSON: ${last_output}")
endif()
run(0 latest --database "${database}")
if(NOT last_output MATCHES "Latest snapshot 2")
  message(FATAL_ERROR "Latest did not select snapshot 2: ${last_output}")
endif()
run(0 diff --from 1 --to 2 --database "${database}")
if(NOT last_output MATCHES "Comparable logical delta: +[+]7 B" OR NOT last_output MATCHES "grew.*example.txt")
  message(FATAL_ERROR "Incorrect CLI growth report: ${last_output}")
endif()
run(0 diff --from 1 --to 2 --json --database "${database}")
string(JSON json_delta GET "${last_output}" logicalDelta)
string(JSON json_files LENGTH "${last_output}" files)
if(NOT json_delta EQUAL 7 OR NOT json_files EQUAL 1)
  message(FATAL_ERROR "Invalid diff JSON: ${last_output}")
endif()
run(1 diff --since 24h --database "${database}")
run(1 diff --since 0h --database "${database}")
run(0 issues --scan 2 --database "${database}")
if(NOT last_output MATCHES "Coverage issues: 0")
  message(FATAL_ERROR "Unexpected fixture issues: ${last_output}")
endif()
run(1 diff --from 2 --to 1 --database "${database}")
run(1 diff --from 1 --to 99 --database "${database}")
run(1 diff --from 1 --to 2 --limit 0 --database "${database}")
run(1 diff --from 1 --to 2 --unknown value --database "${database}")
run(1 scans --database "${fixture}/missing.db")
if(EXISTS "${fixture}/missing.db")
  message(FATAL_ERROR "Read command created a missing database")
endif()
run(0 scan "${fixture}/data" --quiet --database "${database}")
run(0 scan "${fixture}/other" --database "${database}")
run(1 diff --from 1 --to 4 --database "${database}")
run(1 latest --database "${database}")
run(0 latest --path "${fixture}/data" --database "${database}")
run(1 retention --keep 2 --database "${database}")
run(0 scan "${fixture}/data" --quiet --database "${database}")
run(0 scan "${fixture}/data" --quiet --database "${database}")
run(0 retention --path "${fixture}/data" --keep 2 --database "${database}")
if(NOT last_output MATCHES "Would delete snapshot IDs: 1 2 3")
  message(FATAL_ERROR "Retention preview chose wrong snapshots: ${last_output}")
endif()
run(0 issues --scan 1 --database "${database}")
run(0 retention --path "${fixture}/data" --keep 2 --apply --database "${database}")
run(1 issues --scan 1 --database "${database}")
run(0 latest --path "${fixture}/data" --database "${database}")
if(NOT last_output MATCHES "Latest snapshot 6")
  message(FATAL_ERROR "Retention removed newest snapshot: ${last_output}")
endif()
run(0 compact --database "${database}")
run(1 scan "${fixture}/absent" --database "${fixture}/must-not-exist.db")
if(EXISTS "${fixture}/must-not-exist.db")
  message(FATAL_ERROR "Failed scan created a database")
endif()
file(WRITE "${fixture}/not-sqlite.txt" "This is existing user data.")
run(1 scan "${fixture}/data" --database "${fixture}/not-sqlite.txt")
file(READ "${fixture}/not-sqlite.txt" preserved)
if(NOT preserved STREQUAL "This is existing user data.")
  message(FATAL_ERROR "Unrelated file was modified")
endif()
run(0 scan "${fixture}/data" --json-stream --database "${database}")
if(NOT last_output MATCHES "\"type\":\"progress\"" OR NOT last_output MATCHES "\"type\":\"saved\"")
  message(FATAL_ERROR "Scan stream did not contain progress and saved events: ${last_output}")
endif()
run(1 scan "${fixture}/data" --json-stream --cancel-event "Local\\SpaceLedger-nonexistent" --database "${database}")
run(1 scan "${fixture}/data" --json-stream --quiet --database "${database}")
message(STATUS "CLI workflow and invalid-input tests passed; fixtures: ${fixture}")
